.gitignore
.travis.yml
REQUIRE
deps/build.jl
src/GDAL.jl

Closes #4.
@meggart, since this was basically copy paste of your work, you are author of the commit.

Use Conda as binary provider

---

deps/build.jl

@joa-quim: this library will eventually be the common dependency for both RasterIO and OGR-bindings, so I propose moving over the changes from https://github.com/wkearn/RasterIO.jl/pull/21 to this repository. You okay with that?

update list of aliases

---

gen/README.md
gen/doc.jl
gen/rewriter.jl
gen/wrap_gdal.jl
src/C/cpl_error.jl
src/C/cpl_minixml.jl
src/C/cpl_progress.jl
src/C/gdal.jl
src/C/gdal_alg.jl
src/C/gdalwarper.jl
src/C/ogr_api.jl
src/C/ogr_core.jl
src/C/ogr_srs_api.jl
src/gdal_alg.jl
src/gdal_h.jl
src/ogr_api.jl
src/ogr_srs_api.jl

Todo:
It coud be confusing that the input parameters are presented as C types. We could decide to replace it by the Julia conversion, but often these are unhelpful `arg1`, `arg2` as in:
```julia
"""
GDALTermProgress(CPL_UNUSED double dfComplete, CPL_UNUSED const char *pszMessage, void *pProgressArg)
Simple progress report to terminal.
Returns int
"""
function GDALTermProgress(arg1::Cdouble,arg2::Ptr{UInt8},arg3::Ptr{Void})
ccall((:GDALTermProgress,libgdal),Cint,(Cdouble,Ptr{UInt8},Ptr{Void}),arg1,arg2,arg3)
end
```
Part of #5

auto-generated documentation

---

gen/rewriter.jl
src/gdal_alg.jl
src/ogr_api.jl
test/tutorial_vector.jl

closes #15
These functions did not have clashing signatures,
but `create` is not a very helpful name.
Now the only `create` function left is `GDALCreate`.

disambiguate create() functions

---

gen/rewriter.jl
src/C/common.jl
src/C/cpl_error.jl
src/C/gdal.jl
src/C/gdal_alg.jl
src/C/ogr_api.jl
src/C/ogr_core.jl
src/C/ogr_srs_api.jl
src/common.jl
src/gdal_alg.jl
src/gdal_h.jl
src/ogr_api.jl
src/ogr_srs_api.jl

From now on I'd like to stick to official releases if possible.
The usage of NTuple instead of immutable composites in the new Clang.jl cleans up `common.jl` a bit.

update to GDAL 2.1.0 release

---

REQUIRE
deps/build.jl

Minimum GDAL version that Pkg.build("GDAL") now accepts is 2.1
No longer require Conda on Windows

use conda-forge gdal on unix

---

gen/rewriter.jl
src/C/misc.jl
src/GDAL.jl
src/gdal_alg.jl
src/gdal_h.jl
src/gdal_utils.jl
src/gdal_vrt.jl
src/ogr_api.jl
src/ogr_srs_api.jl
test/tutorial_vector.jl

fixes #13 
Commit 5069a757953e4d07b71fae9c854f6d789a6753f9 is perhaps a bit more controversial, so it would be good if @yeesian could sign off on that change. Not sure why we were using `Ptr{Ptr{UInt8}}` instead of `Ptr{Cstring}`.

handle Ptr{Cstring} better

---

src/error.jl
test/error.jl
test/gdal_utils.jl
test/runtests.jl

Fixes #68. This means we cannot use `cplgetlasterror`* functions after an error anymore, but we can just get this information from the GDALError struct, as shown in the tests.
It seems quite neccesary to me to do this, since otherwise you get old error reports back, any time you call a new function that calls `failsafe` to check for errors, as shown in the issue.
Also expands and concentrates the error testing code.

reset the error handler before throwing a GDALError

---

gen/wrap.jl
src/GDAL.jl
src/cpl_conv.jl
src/cpl_error.jl
src/cpl_minixml.jl
src/cpl_progress.jl
src/cpl_virtualmem.jl
src/cpl_vsi.jl
src/error.jl
src/gdal_alg.jl
src/gdal_h.jl
src/gdal_utils.jl
src/gdal_vrt.jl
src/gdalwarper.jl
src/ogr_api.jl
src/ogr_core.jl
src/ogr_srs_api.jl
test/error.jl

Fixes #67.
Currently this errors with `ArgumentError: cannot convert NULL to string` in `unsafe_string`, even though many functions are documented to return NULL in certain cases, that are not errors. This now works similarly to many Base functions like `findfirst`, that return `nothing` in case nothing is found.

return nothing for NULL strings

---

README.md

GDALBuilder is deprecated and this uses now the build scripts provided by Yggdrasil

Change Link to the build script in README

---

Project.toml
test/drivers.jl

A new GDAL_jll build was just released in https://github.com/JuliaPackaging/Yggdrasil/pull/1185. Let's confirm if indeed it fixes #64.

test if JP2OpenJPEG driver is available

---

Project.toml
src/GDAL.jl

stdlib dummy MozillaCACerts_jll does not export `cacert`, which we use in `__init__`

fix on Julia 1.6 for MozillaCACerts_jll

---

Project.toml
test/drivers.jl

Still needs a release of https://github.com/JuliaPackaging/Yggdrasil/pull/1941. 
Because no version has been upped of GDAL_jll, not sure how to actually point to it apart from a git hash. v3.0.4+2 is not a valid version number.

Test new drivers for new GDAL_jll release.

---

test/drivers.jl

Since https://github.com/JuliaPackaging/Yggdrasil/pull/2311 we have a build of GDAL 3.2.0: https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/tag/GDAL-v3.2.0%2B0
The tests were failing due to the GFT and WFS3 drivers not being available anymore. But in https://github.com/OSGeo/gdal/blob/v3.2.0/gdal/NEWS I saw that one is removed and the other renamed:
- Remove GFT driver now that the online service no longer exists
- OAPIF driver (previously WFS3)
Furthermore I added some of the new drivers that I want to make sure are included:
- COG - Cloud Optimized GeoTIFF: https://gdal.org/drivers/raster/cog.html#raster-cog
- OGCAPI: https://gdal.org/drivers/raster/ogcapi.html
- FlatGeoBuf: https://gdal.org/drivers/vector/flatgeobuf.html, see also https://github.com/evetion/FlatGeoBuf.jl
- …

test new drivers included in GDAL 3.2.0

---

test/gdal_jll_utils.jl
test/gdal_utils.jl
test/runtests.jl

This does not fix #95, but tests whether it is fixed, because locally it works fine for me now, so the issue was probably fixed elsewhere.

test running the gdalinfo executable

---

Project.toml

On julia 1.3 to 1.5 we will get v300.201.100, on julia 1.6+ we will get v300.202.100. The GDAL version is the first digit, so v3.2.1.
Fixes #113.

use GDAL_jlls that work across julia versions

---

.gitignore

Actually I want to verify if the MacOS build still works. EDIT: It does. :)

remove /deps/ from .gitignore

---

Project.toml
src/GDAL.jl

Should fix https://github.com/yeesian/ArchGDAL.jl/issues/200

no need to set the certificates on 1.6+

---

README.md

update README on using the utilities

---

gen/GDAL.jl
gen/add_doc.jl
gen/doc.jl
gen/generator.toml
gen/prologue.jl
gen/wrap.jl

I have updated the generator scripts for GDAL.jl, but I ended up finding most of the documentation are in cpp instead of header files, so I post-processed the code to recover doxygen docs in cpp.
Note that Clang.jl is patched (see https://github.com/JuliaInterop/Clang.jl/issues/320)
https://github.com/melonedo/Clang.jl/tree/dump-doc-patch
cc @Gnimuc

Update Clang.jl generator scripts

---

.gitignore
gen/epilogue.jl

Fixes ArchGDAL issue https://github.com/yeesian/ArchGDAL.jl/issues/241 as discussed in PR https://github.com/yeesian/ArchGDAL.jl/pull/245#pullrequestreview-768552407

Deregister custom `gdaljl_errorhandler` at Julia exit

---

gen/Manifest.toml
gen/combine_gdal_doxygen_xml.py
src/GDAL.jl
test/runtests.jl

No functional changes. Some methods are in different order in GDAL.jl.
Previously a custom branch of Clang.jl was needed (see #120). The needed changes have been incorporated in Clang.jl.

regenerate with a released Clang.jl

---

.github/workflows/CI.yml
Project.toml
gen/Manifest.toml
gen/combine_gdal_doxygen_xml.py
gen/generator.toml
src/libgdal.jl

This updates the GDAL, PROJ and GEOS builds used, and reruns the wrapper to add the new functions, and update docstrings.
This upgrades GDAL from 3.2 straight to 3.4, the news can be read here: https://github.com/OSGeo/gdal/blob/v3.4.1/gdal/NEWS.md
The [GDAL_jll](https://github.com/JuliaBinaryWrappers/GDAL_jll.jl) build, updated in [this PR](https://github.com/JuliaPackaging/Yggdrasil/pull/4193), now includes more platforms such as Apple M1, so this should fix #130. These platforms are only supported on Julia 1.6 and above, and to avoid having to maintain a complex build that targets unsupported Julia versions, I dropped support for Julia 1.5 and older. It is worth noting that it is now built with GCC 6 instead of 4 as well.
The diff in libgdal.jl is quite large, but seems reasonable. I …

update to GDAL 3.4.1, require julia 1.6+

---

Project.toml
gen/Manifest.toml
src/libgdal.jl
test/drivers.jl

https://github.com/OSGeo/gdal/blob/v3.5.0/NEWS.md

GDAL 3.5.0

---

README.md
test/drivers.jl

I'd say let's close #134, since we also add a note to the readme that these drivers are not universally available across platforms.
Thanks to @evetion for https://github.com/JuliaPackaging/Yggdrasil/pull/5466.

test HDF5 and netCDF driver availability

---

Project.toml
gen/Manifest.toml
src/libgdal.jl
test/drivers.jl
test/gdal_utils.jl

Released two days ago, and now available in GDAL.jl!
See the release notes: https://github.com/OSGeo/gdal/blob/v3.6.0/NEWS.md
The build also adds support for Arrow and Parquet drivers, thanks to @evetion for Arrow_jll. This also enables making use of https://gdal.org/development/rfc/rfc86_column_oriented_api.html, which can be seen if you look through the large diff for `ogr_l_getarrowstream`.

GDAL 3.6.0

---

README.md
test/gdal_jll_utils.jl

The docstring for the GDAL utils indicates that it is better to use this thread-safe wrapper syntax on Julia 1.6+.
And it is shorter as well.
```
gdalinfo_path(f::Function; adjust_PATH::Bool=true, adjust_LIBPATH::Bool=true)
An ExecutableProduct wrapper that supports the execution of gdalinfo_path.
Example
≡≡≡≡≡≡≡≡≡
gdalinfo_path() do exe
run(`$exe $arguments`)
end
│ Julia 1.3
────────────────────────────────────────────────────────────────────
gdalinfo_path(; adjust_PATH::Bool=true, adjust_LIBPATH::Bool=true) -> Cmd
An ExecutableProduct wrapper that supports the execution of gdalinfo_path. This wrapper is thread-safe and should be preferred on Julia 1.6+.
Example
≡≡≡≡≡≡≡≡≡
run(`$(gdalinfo_path()) $arguments`)
│ Julia 1.6
```
I used R as code block syntax highlighting since the Julia …

use preferred JLL usage syntax

---

src/error.jl

The throw interrupts control flow on the C side, e.g. suppressing the closing of file descriptors when the error is caught by julia. This PR removes it, but leaves the error handler in place, so that printing by GDAL is suppressed. Furthermore, maybe_throw now also throws on fatal errors. Locally, all test pass.
ref https://github.com/rafaqz/Rasters.jl/issues/455

remove throw from gdaljl_errorhandler

---

.github/dependabot.yml
.github/workflows/IntegrationTest.yml

Since ArchGDAL has much more extensive tests, this will catch more issues. Fixes #144.
Also adds dependabot to keep the GitHub Actions up to date, as done here: https://github.com/SciML/MuladdMacro.jl/pull/37

Run downstream tests: ArchGDAL

---

Project.toml

This in turn allows GDAL 3.7.2, which requires PROJ_jll v901 (which is PROJ 9.3).
I want to see about downstream failures.

test GDAL 3.7.2

---

test/gdal_utils.jl

Apparently the ASCII raster headers changed slightly in new GDAL versions. Before there was a space at the beginning of every data line, now there is one at the end. I opted to remove the space, since my editor wants to remove trailing spaces otherwise.

Fix ASCII header tests

---

.github/workflows/CI.yml

So I can just trigger CI manually rather than needing a PR like this to test https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/tag/GDAL-v301.902.300%2B0.

Add workflow_dispatch to CI.yml
